services:
  - type: web
    name: gajanan-utsav
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: SECRET_KEY
        sync: false

      - key: ADMIN_USERNAME
        sync: false

      - key: ADMIN_PASSWORD_HASH
        sync: false

      - key: FIREBASE_CREDENTIALS
        sync: false

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: YOUTUBE_CLIENT_ID
        sync: false

      - key: YOUTUBE_CLIENT_SECRET
        sync: false

      - key: YOUTUBE_REDIRECT_URI
        sync: false
